nb_users:
    resource: "@NBUsersBundle/Resources/config/routing.yml"
    prefix:   /

nb_main:
    resource: "@NBMainBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: NBUsersBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password