<?php

namespace NB\MainBundle\Repository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
    public function  getCitiesByName($nom){
        $qb = $this->createQueryBuilder('c')
            ->select('c.nom as value')
            ->where('c.nom Like :nom')
            ->setParameter('nom', '%'.$nom.'%')
            ->getQuery();

        return $qb->getArrayResult();
    }
    public function  findAllNationalCities(){
        $qb = $this->createQueryBuilder('c')
            ->where('c.type = :type')
            ->setParameter('type', true)
            ->getQuery();

        return $qb->getArrayResult();
    }
    public function  findAllInternationalCities(){
        $qb = $this->createQueryBuilder('c')
            ->where('c.type = :type')
            ->setParameter('type', false)
            ->getQuery();

        return $qb->getArrayResult();
    }
}
