<?php

namespace NB\MainBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTicketNo($TID){

        $queryBuilder = $this
            ->createQueryBuilder('t')
            ->where('t.ticketNo =:TID')
            ->setParameter('TID', $TID);
        // On récupère la Query à partir du QueryBuilder
        $query = $queryBuilder->getQuery();
        // On récupère les résultats à partir de la Query
        $results = $query->getResult();
        //$results = $results;


        // var_dump($results['booked']); exit;
        return $results;


    }
}
