<?php

namespace NB\MainBundle\Repository;

/**
 * TravelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravelRepository extends \Doctrine\ORM\EntityRepository
{

    public function getTravelByRoute($from, $to, $doj)
    {
        $queryBuilder = $this
            ->createQueryBuilder('t')
            ->innerJoin('t.route', 'route')
            ->leftJoin('t.bus', 'bus')
            //    ->leftJoin('t.frequency', 'frequency')
            ->where('route.source = :fc')
            ->andWhere('route.destination = :tc')
            ->andWhere('t.active = :active')
            //->andWhere('(:gd) in f')
            //->andWhere('(:gd) in f')
            ->setParameters(array('fc' => $from, 'tc' => $to, 'active' => true ))
        ;
        // On récupère la Query à partir du QueryBuilder
        $query = $queryBuilder->getQuery();
        // On récupère les résultats à partir de la Query
        $results = $query->getResult();
        // On retourne ces résultats
        $travel = array();
        //var_dump($results[0]->getFrequency()); exit;

        if($results == null){
            return $results;
        }else{
            foreach($results as $key=>$val){
                $frequency = "";

                foreach($val->getFrequency() as $k=>$v){
                    $frequency = $frequency.",".$v->getValue();
                }
               // dump($this->_em->getRepository('NBMainBundle:Promotion')->findActivePromo($val->getRoute()->getId())); exit;
                $travel[] = array(
                    'id' => $val->getId(),
                    'boardingTime' => $val->getBoardingTime(),
                    'arrivalTime' => $val->getArrivalTime(),
                    'price' => $val->getPrice(),
                    'busRegno' => $val->getBus()->getRegno(),
                    'busType' => $val->getBus()->getType(),
                    'busCompany' => $val->getBus()->getCompany()->getNom(),
                    'busCapacity' => $val->getBus()->getCapacity(),
                    'frequency' => $frequency,
                    'comapanyLogo' => $val->getBus()->getCompany()->getLogo(),
                    'bookedSeat' => $val->setBookedSeats($this->_em->getRepository('NBMainBundle:Reservation')->getBookedSeats($val->getBus()->getId(), $doj)),
                    'promo' => $this->_em->getRepository('NBMainBundle:Promotion')->findActivePromo($val->getRoute()->getId()),
                    'promo_price' => $val->getPrice() - $this->_em->getRepository('NBMainBundle:Promotion')->findActivePromo($val->getRoute()->getId())->getMontant()

                );

                //var_dump($val->getBus()->getId()); exit;
            }

        }

        // echo "<pre>";
        // var_dump($travel); exit;

        // var_dump($results); exit;
        return $travel;
    }
}
